name=Kobudei
city=Bucharest
country=RO
timezone=Europe/Bucharest
organizer=Viorel Alexandrescu
members=9
upcomingEvents=0
foundedDate=2026-02-12T11:56:46+02:00
topics=Open Source|New Technology|Cloud Computing|Web Development|Professional Networking|Mobile Development|Computer Programming|Professional Development|Presentations|Public Speaking|Data Science|Software Development|Education & Technology|Web Technology|Big Data
description=Kobudei represents the community of Kotlin developers based in Bucharest, looking to share knowledge on how it helped them write better code. Our goals are to organize events where devs can present their takes on different topics and to create a community where the more seasoned can help newcomers learn how Kotlin can help them in their projects.
sourceUrl=https://www.meetup.com/kobudei/
updatedAt=2026-02-20T11:55:02+00:00
